// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwafpzgvbklixjkhnkrx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13YWZwemd2YmtsaXhqa2hua3J4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3Mzg1MDcsImV4cCI6MjA1OTMxNDUwN30.WAlDHkx_Dp482Q7uP3LxPxXQrc6NesmtBIuadKcDDsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);